const Response = [
  {
    GoalID: Math.floor(Math.random() * 9999999),
    DateCreated: "09:05 AM",
    GoalName: "Instagram Post Update",
    GoalType: "Social Media",
    GoalIcon: "InboxStackIcon",
    DueDate: "Today, 17:00 PM",
    GoalTarget: "Engagement",
    GoalStatus: "Onprogress",
  },
  {
    GoalID: Math.floor(Math.random() * 9999999),
    DateCreated: "09:05 AM",
    GoalName: "Android Studio Course",
    GoalType: "Learning",
    GoalIcon: "CodeBracketIcon",
    DueDate: "25 Dec, 2022",
    GoalTarget: "Intermediate Level",
    GoalStatus: "Onprogress",
  },
  {
    GoalID: Math.floor(Math.random() * 9999999),
    DateCreated: "09:05 AM",
    GoalName: "Business Improvement",
    GoalType: "Business",
    GoalIcon: "ChartPieIcon",
    DueDate: "28 Dec, 2022",
    GoalTarget: "Sales Target",
    GoalStatus: "Onprogress",
  },
  {
    GoalID: Math.floor(Math.random() * 9999999),
    DateCreated: "09:05 AM",
    GoalName: "Home Interior Design",
    GoalType: "Property",
    GoalIcon: "HomeModernIcon",
    DueDate: "06 Nov, 2022",
    GoalTarget: "Interior Stuff",
    GoalStatus: "Done",
  },
  {
    GoalID: Math.floor(Math.random() * 9999999),
    DateCreated: "09:05 AM",
    GoalName: "Mike Air Jordan Shop",
    GoalType: "Fashion shopping",
    GoalIcon: "ShoppingCartIcon",
    DueDate: "06 Nov, 2022",
    GoalTarget: "Upgrade Style",
    GoalStatus: "Done",
  },
];

export default Response;
